### PR TITLE
added check where db connection is passed and still new connection initiated. 

### PR DESCRIPTION
**Pull request by MrSpark2591**
For fixing url parsing error when only db object is passed as parameter and even if you have passed db object with url it was creating new db connection.

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing.. also, can you add a unit test?

**Comment by MrSpark2591** [comment]
yeh sure will check and update

**Comment by MrSpark2591** [comment]
@mcollina added some test cases.Please check and let me know if anything else needs to be done. 
There were some DeprecationWarning from mongo due to old mongo driver. If you need any help in bumping versions let me know. :)

**Comment by MrSpark2591** [comment]
Sure. I will start working on that and update you with new PR for that and also for mqemitter-mongodb.

**Pull request merged**
