### PR TITLE
restore qos0 subscriptions

### PR DESCRIPTION
**Pull request by cordovapolymer**
@mcollina , would this be a viable fix for [Broker should store also subscriptions with QoS 0](https://github.com/mcollina/aedes/issues/174) ?

### CODE REVIEW

**Comment by mcollina** [comment]
Can you send a PR to add a unit test to https://github.com/mcollina/aedes-persistence?

**Comment by mcollina** [comment]
@cordovapolymer this is a pretty old PR. I'm closing this now, feel free to reopen if this is still an issue.

**Comment by GavinDmello** [comment]
@mcollina The code to be tested is in the setup function. Is there a way to test it currently?

**Comment by mcollina** [comment]
I don't understand @GavinDmello, I'm a bit out of touch. Can you clarify?

**Comment by GavinDmello** [comment]
@mcollina I couldn't find a test case which could help check  https://github.com/cordovapolymer/aedes-persistence-mongodb/blob/52d9d82b0f6f2aff6ac073e1a05085a606c91ee1/persistence.js#L43-L78 this private method pertaining to this PR.  Is there any way we can test this code ? 
The _setup method is called from aedes-cached-persistence.

**Comment by mcollina** [comment]
_setup should be called at some point, right? I think we should set up the db so there is a test that fails with this change.

**Pull request closed without merging**
